"""Kratke bilješke o izmjenama (Pomoć → Šta je novo), od najnovije verzije ka starijoj.

Svaka nova verzija mora imati unos na svih 5 jezika; test pada ako `__version__` nema bilješku.
Isti tekst (bs) ide i u opis izdanja na GitHub-u.
"""

from html import escape

# (verzija, datum, {jezik: [stavke]})
CHANGES = [
    ("1.0.0", "8.10.2026", {
        "bs": ["Video Download 1.0: program za računar, Android aplikacija i dodatak za browser dobijaju verziju 1.0 istog dana.",
               "Android aplikacija je upola manja (29 MB umjesto 61 MB): brže preuzimanje i brže slanje prijatelju.",
               "Sve iz probnih verzija je tu: MP4 do najboljeg kvaliteta, MP3, plejliste, isječci, titlovi, poglavlja, roditeljska zaštita i samostalna, potpisana ažuriranja."],
        "en": ["Video Download 1.0: the desktop app, the Android app and the browser extension all reach version 1.0 on the same day.",
               "The Android app is half the size (29 MB instead of 61 MB): faster to download and faster to send to a friend.",
               "Everything from the beta versions is here: MP4 up to the best quality, MP3, playlists, clips, subtitles, chapters, parental controls and signed self-updates."],
        "de": ["Video Download 1.0: Desktop-Programm, Android-App und Browser-Erweiterung erreichen am selben Tag Version 1.0.",
               "Die Android-App ist nur noch halb so groß (29 MB statt 61 MB): schneller geladen und schneller an Freunde geschickt.",
               "Alles aus den Testversionen ist dabei: MP4 in bester Qualität, MP3, Playlists, Ausschnitte, Untertitel, Kapitel, Jugendschutz und signierte automatische Updates."],
        "es": ["Video Download 1.0: el programa de escritorio, la app de Android y la extensión del navegador llegan a la versión 1.0 el mismo día.",
               "La app de Android ocupa la mitad (29 MB en lugar de 61 MB): se descarga y se envía a un amigo más rápido.",
               "Todo lo de las versiones de prueba está aquí: MP4 con la mejor calidad, MP3, listas, fragmentos, subtítulos, capítulos, control parental y actualizaciones automáticas firmadas."],
        "fr": ["Video Download 1.0 : le programme pour ordinateur, l'application Android et l'extension du navigateur passent en version 1.0 le même jour.",
               "L'application Android est deux fois plus légère (29 Mo au lieu de 61 Mo) : plus rapide à télécharger et à envoyer à un ami.",
               "Tout ce qui était dans les versions d'essai est là : MP4 en meilleure qualité, MP3, playlists, extraits, sous-titres, chapitres, contrôle parental et mises à jour automatiques signées."],
    }),
    ("0.9.11", "8.10.2026", {
        "bs": ["Postavke: duga putanja foldera se skraćuje po sredini, a cijela se vidi kad pređeš mišem preko nje.",
               "Format u listi preuzimanja izgleda isto u svakom redu; klik na njega i dalje mijenja format.",
               "Mac: samostalno ažuriranje je pouzdanije (ponovni pokušaj kad macOS kratko odbije otvoriti paket).",
               "Android: aplikacija broji nove instalacije i poziv prijatelju anonimno (samo ukupan broj, vidi Privatnost); sitna čišćenja."],
        "en": ["Settings: a long folder path is shortened in the middle, and the full path shows when you hover over it.",
               "The format in the download list looks the same in every row; clicking it still changes the format.",
               "Mac: self-updating is more reliable (it retries when macOS briefly refuses to open the package).",
               "Android: the app counts new installations and friend invitations anonymously (only a total, see Privacy); small clean-ups."],
        "de": ["Einstellungen: Ein langer Ordnerpfad wird in der Mitte gekürzt; der ganze Pfad erscheint, wenn du mit der Maus darauf zeigst.",
               "Das Format in der Downloadliste sieht in jeder Zeile gleich aus; ein Klick darauf ändert weiterhin das Format.",
               "Mac: Die automatische Aktualisierung ist zuverlässiger (neuer Versuch, wenn macOS das Paket kurz nicht öffnet).",
               "Android: Die App zählt neue Installationen und Einladungen an Freunde anonym (nur eine Gesamtzahl, siehe Datenschutz); kleine Aufräumarbeiten."],
        "es": ["Ajustes: una ruta de carpeta larga se acorta por el medio y la ruta completa aparece al pasar el ratón por encima.",
               "El formato en la lista de descargas se ve igual en cada fila; hacer clic en él sigue cambiando el formato.",
               "Mac: la actualización automática es más fiable (reintenta cuando macOS se niega brevemente a abrir el paquete).",
               "Android: la app cuenta las instalaciones nuevas y las invitaciones a amigos de forma anónima (solo un total, ver Privacidad); pequeñas limpiezas."],
        "fr": ["Paramètres : un long chemin de dossier est raccourci au milieu, et le chemin complet s'affiche au survol de la souris.",
               "Le format dans la liste des téléchargements a le même aspect sur chaque ligne ; un clic dessus change toujours le format.",
               "Mac : la mise à jour automatique est plus fiable (nouvel essai quand macOS refuse brièvement d'ouvrir le paquet).",
               "Android : l'application compte les nouvelles installations et les invitations d'amis de façon anonyme (seulement un total, voir Confidentialité) ; petits nettoyages."],
    }),
    ("0.9.10", "5.10.2026", {
        "bs": ["Poglavlja videa (npr. „0:00 Uvod“) sada ulaze u MP4 i MP3, pa ih plejer prikazuje na traci; isključuje se u Postavkama.",
               "Novo u Postavkama: izrezivanje reklama sponzora (SponsorBlock) iz videa uklanja sponzorske reklame, samoreklamu i „lajkuj i pretplati se“. Isključeno dok ga sam ne uključiš.",
               "Android: MP3 radi i za sajtove bez posebnog zvuka, npr. Instagram (pravi se iz videa); dugme ♪ i kartica Audio više nisu zamrznuti.",
               "Android: na sajtu je i dugme „Dodaj u Obtainium“ za instalaciju i ažuriranje direktno s GitHuba."],
        "en": ["Video chapters (e.g. “0:00 Intro”) now go into MP4 and MP3 files, so players show them on the progress bar; you can turn this off in Settings.",
               "New in Settings: cutting out sponsor ads (SponsorBlock) removes sponsor ads, self-promotion and “like and subscribe” from the video. Off until you turn it on.",
               "Android: MP3 now works for sites without separate audio, such as Instagram (made from the video); the ♪ button and the Audio tab are no longer greyed out.",
               "Android: the website also has an “Add to Obtainium” button to install and update straight from GitHub."],
        "de": ["Videokapitel (z. B. „0:00 Intro“) kommen jetzt in MP4- und MP3-Dateien, sodass Player sie auf der Leiste zeigen; abschaltbar in den Einstellungen.",
               "Neu in den Einstellungen: Sponsorenwerbung herausschneiden (SponsorBlock) entfernt Sponsorenwerbung, Eigenwerbung und „Liken und abonnieren“ aus dem Video. Aus, bis du es einschaltest.",
               "Android: MP3 funktioniert jetzt auch bei Seiten ohne eigene Tonspur, etwa Instagram (aus dem Video erstellt); die ♪-Taste und der Audio-Tab sind nicht mehr ausgegraut.",
               "Android: Auf der Website gibt es jetzt auch „Zu Obtainium hinzufügen“, um direkt von GitHub zu installieren und zu aktualisieren."],
        "es": ["Los capítulos del vídeo (p. ej. «0:00 Intro») ahora van en los archivos MP4 y MP3, y el reproductor los muestra en la barra; se puede desactivar en Ajustes.",
               "Nuevo en Ajustes: recortar anuncios de patrocinadores (SponsorBlock) quita del vídeo los anuncios de patrocinadores, la autopromoción y el «dale like y suscríbete». Desactivado hasta que lo actives.",
               "Android: el MP3 ahora funciona en sitios sin audio separado, como Instagram (se crea a partir del vídeo); el botón ♪ y la pestaña Audio ya no aparecen desactivados.",
               "Android: la web tiene también un botón «Añadir a Obtainium» para instalar y actualizar directamente desde GitHub."],
        "fr": ["Les chapitres de la vidéo (p. ex. « 0:00 Intro ») sont maintenant inclus dans les fichiers MP4 et MP3, et le lecteur les affiche sur la barre ; désactivable dans les Paramètres.",
               "Nouveau dans les Paramètres : couper les pubs des sponsors (SponsorBlock) retire de la vidéo les pubs des sponsors, l'autopromotion et le « like et abonne-toi ». Désactivé tant que vous ne l'activez pas.",
               "Android : le MP3 fonctionne maintenant pour les sites sans piste audio séparée, comme Instagram (créé à partir de la vidéo) ; le bouton ♪ et l'onglet Audio ne sont plus grisés.",
               "Android : le site propose aussi un bouton « Ajouter à Obtainium » pour installer et mettre à jour directement depuis GitHub."],
    }),
    ("0.9.9", "4.10.2026", {
        "bs": ["Novi prozor Postavke (zupčanik desno od „Preuzmi“, ili Fajl → Postavke, Ctrl+,): sve opcije na jednom mjestu, u grupama.",
               "Kartice iznad liste (Sve, U toku, Na čekanju, Završeno, Neuspjelo) i oznake na gotovom fajlu: format, stvarna rezolucija i veličina.",
               "Kad sajt promijeni nešto, Pomoć → Ažuriraj čitač sajtova nudi i noćnu verziju yt-dlp-a s najnovijim popravkama; popravljeno je i automatsko ažuriranje yt-dlp-a.",
               "Prilog sada može i karticom, Apple Payem ili Google Payem, ili preko Ko-fija, bez PayPal naloga.",
               "Traka napretka više ne ostaje na redu koji je završio dok je prozor bio skriven; prazan ekran pominje i dodatak za browser."],
        "en": ["New Settings window (gear next to “Download”, or File → Settings, Ctrl+,): all options in one place, in groups.",
               "Tabs above the list (All, Downloading, Waiting, Finished, Failed) and labels on finished files: format, real resolution and size.",
               "When a site changes something, Help → Update the site reader also offers the nightly yt-dlp with the newest fixes; automatic yt-dlp updates are fixed too.",
               "You can now contribute by card, Apple Pay or Google Pay, or via Ko-fi, without a PayPal account.",
               "The progress bar no longer stays on a row that finished while the window was hidden; the empty screen also mentions the browser extension."],
        "de": ["Neues Fenster Einstellungen (Zahnrad neben „Herunterladen“ oder Datei → Einstellungen, Strg+,): alle Optionen an einem Ort, in Gruppen.",
               "Tabs über der Liste (Alle, Läuft, Wartend, Fertig, Fehlgeschlagen) und Kennzeichen an fertigen Dateien: Format, echte Auflösung und Größe.",
               "Ändert eine Seite etwas, bietet Hilfe → Seiten-Reader aktualisieren auch die Nightly-Version von yt-dlp mit den neuesten Korrekturen an; die automatische yt-dlp-Aktualisierung ist ebenfalls repariert.",
               "Beiträge gehen jetzt auch per Karte, Apple Pay oder Google Pay oder über Ko-fi, ohne PayPal-Konto.",
               "Der Fortschrittsbalken bleibt nicht mehr an einer Zeile, die fertig wurde, während das Fenster verborgen war; der leere Bildschirm erwähnt auch die Browser-Erweiterung."],
        "es": ["Nueva ventana Ajustes (engranaje junto a «Descargar», o Archivo → Ajustes, Ctrl+,): todas las opciones en un solo lugar, por grupos.",
               "Pestañas sobre la lista (Todo, En curso, En espera, Terminados, Fallidos) y etiquetas en los archivos terminados: formato, resolución real y tamaño.",
               "Cuando un sitio cambia algo, Ayuda → Actualizar el lector de sitios ofrece también la versión nightly de yt-dlp con los arreglos más recientes; también se ha corregido la actualización automática de yt-dlp.",
               "Ahora puedes aportar con tarjeta, Apple Pay o Google Pay, o a través de Ko-fi, sin cuenta de PayPal.",
               "La barra de progreso ya no se queda en una fila que terminó con la ventana oculta; la pantalla vacía menciona también la extensión del navegador."],
        "fr": ["Nouvelle fenêtre Paramètres (engrenage à côté de « Télécharger », ou Fichier → Paramètres, Ctrl+,) : toutes les options au même endroit, par groupes.",
               "Onglets au-dessus de la liste (Tout, En cours, En attente, Terminés, Échoués) et étiquettes sur les fichiers terminés : format, résolution réelle et taille.",
               "Quand un site change quelque chose, Aide → Mettre à jour le lecteur de sites propose aussi la version nightly de yt-dlp avec les derniers correctifs ; la mise à jour automatique de yt-dlp est aussi corrigée.",
               "Vous pouvez maintenant contribuer par carte, Apple Pay ou Google Pay, ou via Ko-fi, sans compte PayPal.",
               "La barre de progression ne reste plus sur une ligne terminée pendant que la fenêtre était masquée ; l'écran vide mentionne aussi l'extension du navigateur."],
    }),
    ("0.9.8", "3.10.2026", {
        "bs": ["Preuzimanja → Roditeljska zaštita, po želji zaštićena PIN-om.",
               "Pomoć → Prijavi problem ili prijedlog: otvara e-poruku za autora, uz verziju programa.",
               "Mac se sada ažurira sam, kao Windows: preuzme novu verziju, provjeri naš digitalni potpis i zamijeni program (od sljedećeg izdanja).",
               "Manji instaler (oko 117 MB umjesto 130 MB), bez dijelova koje program ne koristi.",
               "Jasnija poruka kad sajt traži prijavu da bi prikazao objavu."],
        "en": ["Downloads → Parental control, optionally protected by a PIN.",
               "Help → Report a problem or suggestion: opens an e-mail to the author, with the app version.",
               "The Mac version now updates itself like Windows: it downloads the new version, checks our digital signature and replaces the app (from the next release on).",
               "Smaller installer (about 117 MB instead of 130 MB), without parts the app doesn't use.",
               "A clearer message when a site requires you to log in to show a post."],
        "de": ["Downloads → Jugendschutz, auf Wunsch mit PIN geschützt.",
               "Hilfe → Problem oder Vorschlag melden: öffnet eine E-Mail an den Autor, mit der Programmversion.",
               "Die Mac-Version aktualisiert sich jetzt selbst wie unter Windows: Sie lädt die neue Version, prüft unsere digitale Signatur und ersetzt das Programm (ab der nächsten Version).",
               "Kleinerer Installer (etwa 117 MB statt 130 MB), ohne Teile, die das Programm nicht nutzt.",
               "Eine klarere Meldung, wenn eine Seite für einen Beitrag eine Anmeldung verlangt."],
        "es": ["Descargas → Control parental, opcionalmente protegido con PIN.",
               "Ayuda → Informar de un problema o sugerencia: abre un correo al autor, con la versión del programa.",
               "La versión de Mac ahora se actualiza sola como la de Windows: descarga la nueva versión, comprueba nuestra firma digital y sustituye el programa (a partir de la próxima versión).",
               "Instalador más pequeño (unos 117 MB en lugar de 130 MB), sin partes que el programa no usa.",
               "Un mensaje más claro cuando un sitio pide iniciar sesión para mostrar una publicación."],
        "fr": ["Téléchargements → Contrôle parental, protégé par un code PIN si vous le souhaitez.",
               "Aide → Signaler un problème ou une suggestion : ouvre un e-mail à l'auteur, avec la version du programme.",
               "La version Mac se met désormais à jour toute seule comme sous Windows : elle télécharge la nouvelle version, vérifie notre signature numérique et remplace le programme (à partir de la prochaine version).",
               "Programme d'installation plus petit (environ 117 Mo au lieu de 130 Mo), sans les parties inutilisées.",
               "Un message plus clair quand un site demande une connexion pour afficher une publication."],
    }),
    ("0.9.7", "27.9.2026", {
        "bs": ["Razumljive poruke o greškama na jeziku programa (npr. „Video više nije dostupan“, „Nema veze sa sajtom“); tehnička poruka ostaje u oblačiću i u izvještaju o problemu.",
               "Dva preuzimanja nikad ne pišu u isti fajl: ni isti video preko dva linka, ni dugi naslovi istog početka, ni isječci unutar iste sekunde; MP3 istog videa više ne briše već preuzeti MP4.",
               "Red se sam čuva poslije svake izmjene, pa pad programa ili nestanak struje ne gube linkove; „Preuzmi sve“ dok se link još čita kreće čim link stigne.",
               "„Zaustavi“ zaustavlja i pretvaranje u MP3, a „Ukloni sve sa liste“ i „Očisti završene“ ne sklanjaju MP3 koji se još pravi; zatvaranje programa više ne pokreće nova preuzimanja.",
               "Novi pokušaj poslije pucanja veze zaista sačeka 5 sekundi; izvještaj o problemu bolje skriva lozinke i ključeve.",
               "Dodatak za browser pri instalaciji otvara stranicu dobrodošlice (provjera veze s programom, kačenje ikone); veće dugme × i ljepša sličica dok se učitava."],
        "en": ["Clear error messages in the app's language (e.g. “The video is no longer available”, “Can't reach the site”); the technical message stays in the tooltip and in the problem report.",
               "Two downloads never write the same file: not the same video through two links, not long titles that start the same, not clips within the same second; an MP3 of the same video no longer deletes the MP4 you already have.",
               "The queue saves itself after every change, so a crash or power cut doesn't lose links; “Download all” while a link is still being read starts as soon as the link arrives.",
               "“Stop” also stops MP3 conversion, while “Remove all from list” and “Clear finished” keep an MP3 that is still being made; closing the app no longer starts new downloads.",
               "A retry after a dropped connection really waits 5 seconds; the problem report hides passwords and keys more thoroughly.",
               "The browser extension opens a welcome page when installed (checks the connection to the app, shows how to pin the icon); a bigger × button and a nicer picture while the thumbnail loads."],
        "de": ["Verständliche Fehlermeldungen in der Sprache des Programms (z. B. „Das Video ist nicht mehr verfügbar“, „Keine Verbindung zur Seite“); die technische Meldung bleibt im Tooltip und im Problembericht.",
               "Zwei Downloads schreiben nie in dieselbe Datei: weder dasselbe Video über zwei Links noch lange Titel mit gleichem Anfang noch Ausschnitte innerhalb derselben Sekunde; eine MP3 desselben Videos löscht die schon geladene MP4 nicht mehr.",
               "Die Liste speichert sich nach jeder Änderung selbst, daher gehen bei einem Absturz oder Stromausfall keine Links verloren; „Alle herunterladen“, während ein Link noch gelesen wird, startet, sobald der Link da ist.",
               "„Stoppen“ hält auch die MP3-Umwandlung an, während „Alle aus der Liste entfernen“ und „Fertige entfernen“ eine MP3 behalten, die noch entsteht; das Schließen startet keine neuen Downloads mehr.",
               "Ein neuer Versuch nach einem Verbindungsabbruch wartet wirklich 5 Sekunden; der Problembericht verbirgt Passwörter und Schlüssel gründlicher.",
               "Die Browser-Erweiterung öffnet bei der Installation eine Willkommensseite (prüft die Verbindung zum Programm, zeigt das Anheften des Symbols); größere ×-Schaltfläche und schöneres Bild, solange das Vorschaubild lädt."],
        "es": ["Mensajes de error comprensibles en el idioma del programa (p. ej. «El vídeo ya no está disponible», «No se puede conectar con el sitio»); el mensaje técnico sigue en la información emergente y en el informe de problemas.",
               "Dos descargas nunca escriben el mismo archivo: ni el mismo vídeo con dos enlaces, ni títulos largos que empiezan igual, ni fragmentos dentro del mismo segundo; un MP3 del mismo vídeo ya no borra el MP4 que ya tenías.",
               "La cola se guarda sola tras cada cambio, así que un cierre inesperado o un corte de luz no pierden enlaces; «Descargar todo» mientras se lee un enlace empieza en cuanto llega el enlace.",
               "«Detener» también detiene la conversión a MP3, mientras que «Quitar todo de la lista» y «Quitar terminados» conservan un MP3 que aún se está creando; cerrar el programa ya no inicia descargas nuevas.",
               "Un reintento tras cortarse la conexión espera de verdad 5 segundos; el informe de problemas oculta mejor contraseñas y claves.",
               "La extensión del navegador abre una página de bienvenida al instalarse (comprueba la conexión con el programa y muestra cómo fijar el icono); botón × más grande y una imagen más bonita mientras carga la miniatura."],
        "fr": ["Messages d'erreur compréhensibles dans la langue du programme (p. ex. « La vidéo n'est plus disponible », « Impossible de joindre le site ») ; le message technique reste dans l'info-bulle et dans le rapport de problème.",
               "Deux téléchargements n'écrivent jamais le même fichier : ni la même vidéo via deux liens, ni de longs titres qui commencent pareil, ni des extraits dans la même seconde ; un MP3 de la même vidéo ne supprime plus le MP4 déjà téléchargé.",
               "La file s'enregistre toute seule après chaque modification : un plantage ou une coupure de courant ne fait perdre aucun lien ; « Tout télécharger » pendant la lecture d'un lien démarre dès que le lien arrive.",
               "« Arrêter » arrête aussi la conversion en MP3, tandis que « Tout retirer de la liste » et « Effacer les terminés » gardent un MP3 encore en cours ; fermer le programme ne lance plus de nouveaux téléchargements.",
               "Une nouvelle tentative après une coupure de connexion attend vraiment 5 secondes ; le rapport de problème masque mieux les mots de passe et les clés.",
               "L'extension du navigateur ouvre une page d'accueil à l'installation (vérifie la connexion au programme, montre comment épingler l'icône) ; bouton × plus grand et une plus belle image pendant le chargement de la miniature."],
    }),
    ("0.9.6", "26.9.2026", {
        "bs": ["Ažuriranja su digitalno potpisana: program instalira samo novu verziju koju smo mi potpisali, čak i ako neko podmetne drugi fajl na mjesto objave.",
               "Pri prvom pokretanju kratka obavijest da program prati kopirane linkove, s dugmetom da se to odmah isključi.",
               "Zaostali privremeni fajlovi s kolačićima (poslije naglog prekida) brišu se pri sljedećem pokretanju; duge liste troše manje memorije.",
               "Veza s dodatkom u pretraživaču otpornija je na spore i zaglavljene zahtjeve."],
        "en": ["Updates are digitally signed: the app installs only a new version signed by us, even if someone swaps the file where it is published.",
               "On first start, a short notice that the app watches copied links, with a button to turn it off right away.",
               "Leftover temporary cookie files (after a sudden shutdown) are removed on the next start; long lists use less memory.",
               "The connection with the browser add-on copes better with slow or stuck requests."],
        "de": ["Updates sind digital signiert: Das Programm installiert nur eine von uns signierte neue Version, selbst wenn jemand die Datei am Veröffentlichungsort austauscht.",
               "Beim ersten Start ein kurzer Hinweis, dass das Programm kopierte Links beobachtet, mit einer Schaltfläche zum sofortigen Abschalten.",
               "Übrig gebliebene temporäre Cookie-Dateien (nach einem plötzlichen Abbruch) werden beim nächsten Start gelöscht; lange Listen brauchen weniger Speicher.",
               "Die Verbindung zum Browser-Add-on kommt besser mit langsamen oder hängenden Anfragen zurecht."],
        "es": ["Las actualizaciones están firmadas digitalmente: el programa solo instala una versión nueva firmada por nosotros, aunque alguien cambie el archivo donde se publica.",
               "En el primer inicio, un breve aviso de que el programa vigila los enlaces copiados, con un botón para desactivarlo en el acto.",
               "Los archivos temporales de cookies que quedan (tras un cierre repentino) se borran en el siguiente inicio; las listas largas usan menos memoria.",
               "La conexión con el complemento del navegador resiste mejor las peticiones lentas o bloqueadas."],
        "fr": ["Les mises à jour sont signées numériquement : le programme n'installe qu'une nouvelle version signée par nous, même si quelqu'un remplace le fichier publié.",
               "Au premier démarrage, un court avis indiquant que le programme surveille les liens copiés, avec un bouton pour le désactiver tout de suite.",
               "Les fichiers temporaires de cookies restants (après un arrêt brutal) sont supprimés au démarrage suivant ; les longues listes utilisent moins de mémoire.",
               "La connexion avec le module du navigateur résiste mieux aux requêtes lentes ou bloquées."],
    }),
    ("0.9.5", "26.9.2026", {
        "bs": ["1080p, 720p i 480p dobijaju oznaku u imenu fajla, pa različit kvalitet istog videa više nije „već preuzeto“.",
               "Dva videa istog naslova (ime fajla bez ID-a) više se ne miješaju; isti video pokrenut dvaput istovremeno čeka da prvi završi.",
               "„Završeno“ tek kad gotov fajl postoji i može se pročitati; pretvaranje u MP3 se uvijek može prekinuti.",
               "Zatvaranje programa ne zamrzava prozor; ažuriranje čeka i pretvaranja u MP3."],
        "en": ["1080p, 720p and 480p get a tag in the file name, so a different quality of the same video is no longer \u201calready downloaded\u201d.",
               "Two videos with the same title (file name without ID) no longer get mixed up; the same video started twice at once waits for the first one.",
               "\u201cFinished\u201d only when the file exists and can be read; MP3 conversion can always be stopped.",
               "Closing the app no longer freezes the window; updating also waits for MP3 conversions."],
        "de": ["1080p, 720p und 480p erhalten eine Markierung im Dateinamen, daher gilt eine andere Qualität desselben Videos nicht mehr als \u201ebereits heruntergeladen\u201c.",
               "Zwei Videos mit gleichem Titel (Dateiname ohne ID) werden nicht mehr verwechselt; dasselbe Video, das zweimal gleichzeitig startet, wartet auf das erste.",
               "\u201eFertig\u201c erst, wenn die Datei existiert und lesbar ist; die MP3-Umwandlung lässt sich immer abbrechen.",
               "Das Schließen friert das Fenster nicht mehr ein; das Update wartet auch auf MP3-Umwandlungen."],
        "es": ["1080p, 720p y 480p llevan una marca en el nombre del archivo, así que otra calidad del mismo vídeo ya no es «ya descargado».",
               "Dos vídeos con el mismo título (nombre sin ID) ya no se mezclan; el mismo vídeo iniciado dos veces a la vez espera al primero.",
               "«Terminado» solo cuando el archivo existe y se puede leer; la conversión a MP3 siempre se puede detener.",
               "Cerrar el programa ya no congela la ventana; la actualización también espera a las conversiones a MP3."],
        "fr": ["1080p, 720p et 480p reçoivent une marque dans le nom du fichier : une autre qualité de la même vidéo n'est plus « déjà téléchargée ».",
               "Deux vidéos du même titre (nom sans ID) ne se mélangent plus ; la même vidéo lancée deux fois en même temps attend la première.",
               "« Terminé » seulement quand le fichier existe et est lisible ; la conversion en MP3 peut toujours être arrêtée.",
               "La fermeture ne fige plus la fenêtre ; la mise à jour attend aussi les conversions en MP3."],
    }),
    ("0.9.4", "26.9.2026", {
        "bs": ["Stabilnost: isti link se može ponovo dodati odmah poslije „Zaustavi“.",
               "Ažuriranje čitača sajtova (yt-dlp) više ne briše verziju koja radi; ako nova ne radi, program se sam vraća na prethodnu.",
               "Oštećena istorija ili red ne obaraju program; ako čuvanje ne uspije, program to javi.",
               "Deinstalacija uklanja i vezu s Firefoxom; ograničenje brzine se dijeli samo na preuzimanja koja stvarno rade."],
        "en": ["Stability: the same link can be added again right after \u201cStop\u201d.",
               "Updating the site reader (yt-dlp) no longer deletes the version in use; if the new one doesn't work, the app goes back to the previous one.",
               "A damaged history or queue no longer crashes the app; if saving fails, the app tells you.",
               "Uninstalling also removes the Firefox connection; the speed limit is shared only among downloads that are actually running."],
        "de": ["Stabilität: Derselbe Link kann direkt nach \u201eStopp\u201c erneut hinzugefügt werden.",
               "Das Aktualisieren des Seitenlesers (yt-dlp) löscht die laufende Version nicht mehr; funktioniert die neue nicht, kehrt das Programm zur vorherigen zurück.",
               "Ein beschädigter Verlauf oder eine beschädigte Liste bringt das Programm nicht mehr zum Absturz; schlägt das Speichern fehl, meldet es das Programm.",
               "Die Deinstallation entfernt auch die Firefox-Verbindung; das Tempolimit wird nur auf tatsächlich laufende Downloads verteilt."],
        "es": ["Estabilidad: el mismo enlace se puede volver a añadir justo después de «Detener».",
               "Actualizar el lector de sitios (yt-dlp) ya no borra la versión en uso; si la nueva no funciona, el programa vuelve a la anterior.",
               "Un historial o una cola dañados ya no bloquean el programa; si no se puede guardar, el programa lo avisa.",
               "La desinstalación también quita la conexión con Firefox; el límite de velocidad se reparte solo entre las descargas que realmente están en curso."],
        "fr": ["Stabilité : le même lien peut être ajouté à nouveau juste après « Arrêter ».",
               "La mise à jour du lecteur de sites (yt-dlp) ne supprime plus la version utilisée ; si la nouvelle ne fonctionne pas, le programme revient à la précédente.",
               "Un historique ou une file endommagés ne font plus planter le programme ; si l'enregistrement échoue, le programme le signale.",
               "La désinstallation supprime aussi la connexion à Firefox ; la limite de vitesse n'est partagée qu'entre les téléchargements réellement en cours."],
    }),
    ("0.9.3", "26.9.2026", {
        "bs": ["Pomoć → Preuzimanje iz browsera: dugmad „Kopiraj putanju foldera“, „Otvori folder“ i otvaranje stranice dodataka u Edge-u ili Chrome-u; uputstvo sa slikama na sajtu.",
               "Priprema za dodatak u Firefoxu (bez developer moda)."],
        "en": ["Help → Downloading from the browser: buttons “Copy the folder path”, “Open the folder” and opening the extensions page in Edge or Chrome; illustrated guide on the website.",
               "Groundwork for the Firefox extension (without developer mode)."],
        "de": ["Hilfe → Aus dem Browser herunterladen: Schaltflächen „Ordnerpfad kopieren“, „Ordner öffnen“ und Öffnen der Erweiterungsseite in Edge oder Chrome; bebilderte Anleitung auf der Website.",
               "Vorbereitung für die Firefox-Erweiterung (ohne Entwicklermodus)."],
        "es": ["Ayuda → Descargar desde el navegador: botones «Copiar la ruta de la carpeta», «Abrir la carpeta» y abrir la página de extensiones en Edge o Chrome; guía con imágenes en el sitio web.",
               "Preparación para la extensión de Firefox (sin modo de desarrollador)."],
        "fr": ["Aide → Télécharger depuis le navigateur : boutons « Copier le chemin du dossier », « Ouvrir le dossier » et ouverture de la page des extensions dans Edge ou Chrome ; guide illustré sur le site.",
               "Préparation de l'extension Firefox (sans mode développeur)."],
    }),
    ("0.9.2", "26.9.2026", {
        "bs": ["Titlovi: kad video nema ručne titlove, uzimaju se automatski; titl se čuva i kao .srt pored videa (s istim imenom, pa ga playeri sami učitaju), a ne samo u MP4.",
               "Ako titl ne može da se preuzme, video se ipak preuzme, uz napomenu „bez titlova“.",
               "Na engleskom se brojevi pišu s tačkom (8.4 MB/s)."],
        "en": ["Subtitles: when a video has no manual subtitles, automatic ones are used; the subtitle is also saved as an .srt next to the video (same name, so players load it on their own), not only inside the MP4.",
               "If a subtitle can't be downloaded, the video is still downloaded, marked “no subtitles”.",
               "In English, numbers use a decimal point (8.4 MB/s)."],
        "de": ["Untertitel: Hat ein Video keine manuellen Untertitel, werden automatische verwendet; der Untertitel wird auch als .srt neben dem Video gespeichert (gleicher Name, damit Player ihn selbst laden), nicht nur im MP4.",
               "Kann ein Untertitel nicht geladen werden, wird das Video trotzdem heruntergeladen, mit dem Hinweis „ohne Untertitel“.",
               "Im Englischen werden Zahlen mit Punkt geschrieben (8.4 MB/s)."],
        "es": ["Subtítulos: si un vídeo no tiene subtítulos manuales, se usan los automáticos; el subtítulo también se guarda como .srt junto al vídeo (mismo nombre, para que los reproductores lo carguen solos), no solo dentro del MP4.",
               "Si un subtítulo no se puede descargar, el vídeo se descarga igualmente, con la nota «sin subtítulos».",
               "En inglés, los números usan punto decimal (8.4 MB/s)."],
        "fr": ["Sous-titres : si une vidéo n'a pas de sous-titres manuels, les automatiques sont utilisés ; le sous-titre est aussi enregistré en .srt à côté de la vidéo (même nom, pour que les lecteurs le chargent seuls), pas seulement dans le MP4.",
               "Si un sous-titre ne peut pas être téléchargé, la vidéo est quand même téléchargée, avec la mention « sans sous-titres ».",
               "En anglais, les nombres utilisent un point décimal (8.4 MB/s)."],
    }),
    ("0.9.1", "25.9.2026", {
        "bs": ["Nova adresa projekta: github.com/abnps/video-download i sajt abnps.github.io/video-download."],
        "en": ["New project address: github.com/abnps/video-download and the website abnps.github.io/video-download."],
        "de": ["Neue Projektadresse: github.com/abnps/video-download und die Website abnps.github.io/video-download."],
        "es": ["Nueva dirección del proyecto: github.com/abnps/video-download y el sitio abnps.github.io/video-download."],
        "fr": ["Nouvelle adresse du projet : github.com/abnps/video-download et le site abnps.github.io/video-download."],
    }),
    ("0.9.0", "25.9.2026", {
        "bs": ["Tamna tema: Pomoć → Tema (svijetla, tamna ili kao Windows).",
               "Obavještenje u Windowsu kad se sva preuzimanja završe (Preuzimanja → Obavijesti me…).",
               "Napredak se vidi i na dugmetu programa u traci zadataka.",
               "Istorija: pretraga po naslovu, linku ili imenu fajla i izbor video, zvuk ili obrisani fajlovi.",
               "Ime fajla po izboru: Preuzimanja → Ime fajla (npr. „Izvođač - Naslov“)."],
        "en": ["Dark theme: Help → Theme (light, dark or same as Windows).",
               "A Windows notification when all downloads have finished (Downloads → Notify me…).",
               "Progress is also shown on the program's taskbar button.",
               "History: search by title, link or file name and filter by video, audio or deleted files.",
               "Choose the file name: Downloads → File name (e.g. \u201cArtist - Title\u201d)."],
        "de": ["Dunkles Design: Hilfe → Design (hell, dunkel oder wie Windows).",
               "Eine Windows-Benachrichtigung, wenn alle Downloads fertig sind (Downloads → Benachrichtigen…).",
               "Der Fortschritt ist auch auf der Schaltfläche in der Taskleiste zu sehen.",
               "Verlauf: Suche nach Titel, Link oder Dateiname und Filter nach Video, Audio oder gelöschten Dateien.",
               "Dateiname wählbar: Downloads → Dateiname (z. B. \u201eInterpret - Titel\u201c)."],
        "es": ["Tema oscuro: Ayuda → Tema (claro, oscuro o como Windows).",
               "Una notificación de Windows cuando terminan todas las descargas (Descargas → Avisarme…).",
               "El progreso también se ve en el botón del programa en la barra de tareas.",
               "Historial: búsqueda por título, enlace o nombre de archivo y filtro por vídeo, audio o archivos borrados.",
               "Nombre del archivo a elegir: Descargas → Nombre del archivo (p. ej. «Artista - Título»)."],
        "fr": ["Thème sombre : Aide → Thème (clair, sombre ou comme Windows).",
               "Une notification Windows quand tous les téléchargements sont terminés (Téléchargements → Me prévenir…).",
               "La progression s'affiche aussi sur le bouton du programme dans la barre des tâches.",
               "Historique : recherche par titre, lien ou nom de fichier et filtre vidéo, audio ou fichiers supprimés.",
               "Nom du fichier au choix : Téléchargements → Nom du fichier (p. ex. « Artiste - Titre »)."],
    }),
    ("0.8.0", "25.9.2026", {
        "bs": ["Animirana traka napretka: glatko klizi, preko nje prelazi sjaj, plava je za video i ljubičasta za zvuk, "
               "dok se video i zvuk spajaju klizi lijevo-desno, a na kraju zazeleni."],
        "en": ["Animated progress bar: it glides smoothly with a moving shine, blue for video and purple for audio, "
               "slides back and forth while video and audio are merged, and turns green at the end."],
        "de": ["Animierter Fortschrittsbalken: gleitet sanft mit wanderndem Glanz, blau für Video und lila für Audio, "
               "läuft beim Zusammenführen von Video und Audio hin und her und wird am Ende grün."],
        "es": ["Barra de progreso animada: avanza con suavidad y un brillo que la recorre, azul para vídeo y morada para audio, "
               "se desliza de un lado a otro mientras se unen vídeo y audio y al final se vuelve verde."],
        "fr": ["Barre de progression animée : elle avance en douceur avec un reflet qui la parcourt, bleue pour la vidéo et violette pour l'audio, "
               "glisse d'un côté à l'autre pendant la fusion vidéo et audio et devient verte à la fin."],
    }),
    ("0.7.9", "24.9.2026", {
        "bs": ["Link koji nije video ni audio više nikad ne pravi karticu, ni preko „Zalijepi“ ni iz browsera; "
               "poruka je samo u statusnoj traci. Takva stara kartica se ne vraća pri pokretanju."],
        "en": ["A link that isn't a video or audio never creates a card any more, not via “Paste” nor from the browser; "
               "the message is only in the status bar. Such an old card is not restored at startup."],
        "de": ["Ein Link, der kein Video oder Audio ist, erzeugt nie mehr eine Karte, weder über „Einfügen“ noch aus dem Browser; "
               "die Meldung steht nur in der Statusleiste. Eine solche alte Karte wird beim Start nicht wiederhergestellt."],
        "es": ["Un enlace que no es un vídeo ni un audio ya nunca crea una tarjeta, ni con «Pegar» ni desde el navegador; "
               "el mensaje aparece solo en la barra de estado. Una tarjeta antigua así no se restaura al iniciar."],
        "fr": ["Un lien qui n'est ni une vidéo ni un audio ne crée plus jamais de carte, ni via « Coller » ni depuis le navigateur ; "
               "le message s'affiche seulement dans la barre d'état. Une telle ancienne carte n'est pas restaurée au démarrage."],
    }),
    ("0.7.8", "24.9.2026", {
        "bs": ["Link koji nije video ni audio (npr. .exe, .zip, .pdf ili obična stranica) više ne pravi karticu "
               "kad se samo kopira; ako ga zalijepiš sam, poruka jasno kaže zašto. Direktni .mp3 i .mp4 linkovi rade kao i prije."],
        "en": ["A link that isn't a video or audio (e.g. .exe, .zip, .pdf or a plain page) no longer creates a card "
               "when it's just copied; if you paste it yourself, the message clearly says why. Direct .mp3 and .mp4 links work as before."],
        "de": ["Ein Link, der kein Video oder Audio ist (z. B. .exe, .zip, .pdf oder eine normale Seite), erzeugt beim bloßen "
               "Kopieren keine Karte mehr; fügst du ihn selbst ein, sagt die Meldung klar, warum. Direkte .mp3- und .mp4-Links funktionieren wie bisher."],
        "es": ["Un enlace que no es un vídeo ni un audio (p. ej. .exe, .zip, .pdf o una página normal) ya no crea una tarjeta "
               "al copiarlo; si lo pegas tú, el mensaje explica claramente por qué. Los enlaces directos .mp3 y .mp4 funcionan como antes."],
        "fr": ["Un lien qui n'est ni une vidéo ni un audio (p. ex. .exe, .zip, .pdf ou une page ordinaire) ne crée plus de carte "
               "quand il est simplement copié ; si tu le colles toi-même, le message explique clairement pourquoi. Les liens directs .mp3 et .mp4 fonctionnent comme avant."],
    }),
    ("0.7.7", "24.9.2026", {
        "bs": ["Prozor „Podrži projekat“ ima i QR kod za prilog telefonom, pored dugmeta."],
        "en": ["The “Support the project” window also has a QR code for contributing by phone, next to the button."],
        "de": ["Das Fenster „Projekt unterstützen“ hat neben der Schaltfläche auch einen QR-Code für Beiträge per Handy."],
        "es": ["La ventana «Apoyar el proyecto» también tiene un código QR para aportar con el móvil, junto al botón."],
        "fr": ["La fenêtre « Soutenir le projet » a aussi un QR code pour contribuer depuis le téléphone, à côté du bouton."],
    }),
    ("0.7.6", "24.9.2026", {
        "bs": ["„Podrži projekat“ otvara PayPal stranicu za prilog, gdje sam biraš iznos."],
        "en": ["\u201cSupport the project\u201d opens a PayPal contribution page where you choose the amount."],
        "de": ["\u201eProjekt unterstützen\u201c öffnet eine PayPal-Seite für Beiträge, auf der du den Betrag selbst wählst."],
        "es": ["«Apoyar el proyecto» abre una página de aportaciones de PayPal donde eliges el importe."],
        "fr": ["« Soutenir le projet » ouvre une page de contribution PayPal où tu choisis le montant."],
    }),
    ("0.7.5", "24.9.2026", {
        "bs": ["„Podrži projekat“: dobrovoljni prilog preko PayPal-a (statusna traka, Pomoć, povremeni podsjetnik koji se može sakriti). Prilog ništa ne otključava."],
        "en": ["\u201cSupport the project\u201d: voluntary contribution via PayPal (status bar, Help, an occasional reminder you can hide). A contribution unlocks nothing."],
        "de": ["\u201eProjekt unterstützen\u201c: freiwilliger Beitrag über PayPal (Statusleiste, Hilfe, gelegentliche ausblendbare Erinnerung). Ein Beitrag schaltet nichts frei."],
        "es": ["«Apoyar el proyecto»: aportación voluntaria por PayPal (barra de estado, Ayuda, un recordatorio ocasional que se puede ocultar). La aportación no desbloquea nada."],
        "fr": ["« Soutenir le projet » : contribution volontaire via PayPal (barre d'état, Aide, un rappel occasionnel masquable). Une contribution ne débloque rien."],
    }),
    ("0.7.4", "24.9.2026", {
        "bs": ["Licencni ugovor, uslovi korištenja i politika privatnosti na 5 jezika u instaleru i u Pomoć \u2192 Ugovori i licence.",
               "Puni tekstovi licenci komponenti (FFmpeg, Qt, Node.js, yt-dlp…) u folderu „licenses\u201c."],
        "en": ["License agreement, terms of use and privacy policy in 5 languages, in the installer and under Help \u2192 Agreements and licenses.",
               "Full license texts of the components (FFmpeg, Qt, Node.js, yt-dlp…) in the \u201clicenses\u201d folder."],
        "de": ["Lizenzvertrag, Nutzungsbedingungen und Datenschutzerklärung in 5 Sprachen, im Installer und unter Hilfe \u2192 Verträge und Lizenzen.",
               "Vollständige Lizenztexte der Komponenten (FFmpeg, Qt, Node.js, yt-dlp…) im Ordner \u201elicenses\u201c."],
        "es": ["Contrato de licencia, condiciones de uso y política de privacidad en 5 idiomas, en el instalador y en Ayuda \u2192 Contratos y licencias.",
               "Textos completos de las licencias de los componentes (FFmpeg, Qt, Node.js, yt-dlp…) en la carpeta «licenses»."],
        "fr": ["Contrat de licence, conditions d'utilisation et politique de confidentialité en 5 langues, dans l'installateur et dans Aide \u2192 Contrats et licences.",
               "Textes complets des licences des composants (FFmpeg, Qt, Node.js, yt-dlp…) dans le dossier « licenses »."],
    }),
    ("0.7.3", "24.9.2026", {
        "bs": ["Dugme „MP3“ na kartici preuzetog MP4 videa, pored foldera: pretvara video u MP3, a MP4 ostaje."],
        "en": ["“MP3” button on the card of a downloaded MP4 video, next to the folder: converts it to MP3 and keeps the MP4."],
        "de": ["Schaltfläche „MP3“ auf der Karte eines geladenen MP4-Videos, neben dem Ordner: wandelt in MP3 um, die MP4 bleibt."],
        "es": ["Botón «MP3» en la tarjeta de un vídeo MP4 descargado, junto a la carpeta: lo convierte a MP3 y conserva el MP4."],
        "fr": ["Bouton « MP3 » sur la carte d'une vidéo MP4 téléchargée, à côté du dossier : la convertit en MP3 et garde le MP4."],
    }),
    ("0.7.2", "24.9.2026", {
        "bs": ["Uslovi korištenja: prihvataju se u instaleru i stoje u Pomoć → Uslovi korištenja."],
        "en": ["Terms of use: accepted in the installer and available under Help → Terms of use."],
        "de": ["Nutzungsbedingungen: werden im Installer akzeptiert und stehen unter Hilfe → Nutzungsbedingungen."],
        "es": ["Condiciones de uso: se aceptan en el instalador y están en Ayuda → Condiciones de uso."],
        "fr": ["Conditions d'utilisation : acceptées dans l'installateur et disponibles dans Aide → Conditions d'utilisation."],
    }),
    ("0.7.1", "23.9.2026", {
        "bs": ["Pomoć → Šta je novo: kratke bilješke o izmjenama po verzijama."],
        "en": ["Help → What's new: short notes about the changes in each version."],
        "de": ["Hilfe → Was ist neu: kurze Hinweise zu den Änderungen jeder Version."],
        "es": ["Ayuda → Novedades: notas breves sobre los cambios de cada versión."],
        "fr": ["Aide → Nouveautés : courtes notes sur les changements de chaque version."],
    }),
    ("0.7.0", "23.9.2026", {
        "bs": ["Isječak videa (od–do) iz menija formata u redu.",
               "Titlovi uz video i sličica kao omot fajla.",
               "Ograničenje brzine i opcija da link videa iz plejliste preuzme cijelu plejlistu.",
               "MP3 u meniju desnog klika u browseru.",
               "Instaler je manji za trećinu (136 MB umjesto 198 MB)."],
        "en": ["Video clip (from–to) from the format menu of a row.",
               "Subtitles with the video and the thumbnail as file cover.",
               "Speed limit, and an option for a video link from a playlist to download the whole playlist.",
               "MP3 in the browser right-click menu.",
               "The installer is a third smaller (136 MB instead of 198 MB)."],
        "de": ["Videoausschnitt (von–bis) über das Formatmenü einer Zeile.",
               "Untertitel zum Video und Vorschaubild als Cover.",
               "Geschwindigkeitslimit und Option, bei einem Videolink aus einer Playlist die ganze Playlist zu laden.",
               "MP3 im Rechtsklickmenü des Browsers.",
               "Das Installationsprogramm ist ein Drittel kleiner (136 MB statt 198 MB)."],
        "es": ["Fragmento de vídeo (desde–hasta) desde el menú de formato de una fila.",
               "Subtítulos con el vídeo y la miniatura como portada.",
               "Límite de velocidad y opción para que un enlace de vídeo de una lista descargue la lista completa.",
               "MP3 en el menú contextual del navegador.",
               "El instalador es un tercio más pequeño (136 MB en lugar de 198 MB)."],
        "fr": ["Extrait vidéo (de–à) depuis le menu de format d'une ligne.",
               "Sous-titres avec la vidéo et miniature comme pochette.",
               "Limite de vitesse et option pour qu'un lien vidéo d'une playlist télécharge toute la playlist.",
               "MP3 dans le menu contextuel du navigateur.",
               "L'installateur est plus petit d'un tiers (136 Mo au lieu de 198 Mo)."],
    }),
    ("0.6.2", "23.9.2026", {
        "bs": ["Ažuriranje radi bez GitHub naloga i bez programa gh."],
        "en": ["Updating works without a GitHub account and without the gh program."],
        "de": ["Aktualisierung funktioniert ohne GitHub-Konto und ohne das Programm gh."],
        "es": ["La actualización funciona sin cuenta de GitHub y sin el programa gh."],
        "fr": ["La mise à jour fonctionne sans compte GitHub et sans le programme gh."],
    }),
    ("0.6.1", "22.9.2026", {
        "bs": ["Dugme „Preuzmi kao MP3“ u prozoru dodatka za browser."],
        "en": ["“Download as MP3” button in the browser extension window."],
        "de": ["Schaltfläche „Als MP3 herunterladen“ im Fenster der Browsererweiterung."],
        "es": ["Botón «Descargar como MP3» en la ventana de la extensión del navegador."],
        "fr": ["Bouton « Télécharger en MP3 » dans la fenêtre de l'extension du navigateur."],
    }),
    ("0.6.0", "22.9.2026", {
        "bs": ["Kopiran link sam ulazi u red.",
               "Red i istorija preuzimanja se pamte između pokretanja.",
               "Pomoć → Sačuvaj izvještaj o problemu."],
        "en": ["A copied link goes into the queue by itself.",
               "The queue and download history are kept between sessions.",
               "Help → Save a problem report."],
        "de": ["Ein kopierter Link kommt von selbst in die Liste.",
               "Liste und Download-Verlauf bleiben zwischen Sitzungen erhalten.",
               "Hilfe → Problembericht speichern."],
        "es": ["Un enlace copiado entra solo en la cola.",
               "La cola y el historial de descargas se conservan entre sesiones.",
               "Ayuda → Guardar un informe del problema."],
        "fr": ["Un lien copié entre tout seul dans la file.",
               "La file et l'historique des téléchargements sont conservés entre les sessions.",
               "Aide → Enregistrer un rapport de problème."],
    }),
    ("0.5.7", "17.9.2026", {
        "bs": ["Više istovremenih preuzimanja (1–4).",
               "Kad veza pukne, preuzimanje se samo ponavlja do 3 puta."],
        "en": ["Several simultaneous downloads (1–4).",
               "When the connection drops, the download is retried up to 3 times."],
        "de": ["Mehrere gleichzeitige Downloads (1–4).",
               "Bei Verbindungsabbruch wird der Download bis zu 3-mal wiederholt."],
        "es": ["Varias descargas simultáneas (1–4).",
               "Si se corta la conexión, la descarga se reintenta hasta 3 veces."],
        "fr": ["Plusieurs téléchargements simultanés (1–4).",
               "En cas de coupure, le téléchargement est relancé jusqu'à 3 fois."],
    }),
    ("0.5.6", "17.9.2026", {
        "bs": ["„Zaustavi“ reaguje odmah, i dok se link još čita."],
        "en": ["“Stop” reacts at once, even while a link is still being read."],
        "de": ["„Stopp“ reagiert sofort, auch während ein Link noch gelesen wird."],
        "es": ["«Detener» responde al instante, incluso mientras se lee un enlace."],
        "fr": ["« Arrêter » réagit tout de suite, même pendant la lecture d'un lien."],
    }),
    ("0.5.5", "17.9.2026", {
        "bs": ["Preuzimanje desnim klikom u browseru (link, video, video koji se pušta)."],
        "en": ["Download with a right-click in the browser (link, video, playing video)."],
        "de": ["Herunterladen per Rechtsklick im Browser (Link, Video, laufendes Video)."],
        "es": ["Descarga con clic derecho en el navegador (enlace, vídeo, vídeo en reproducción)."],
        "fr": ["Téléchargement par clic droit dans le navigateur (lien, vidéo, vidéo en cours)."],
    }),
    ("0.5.4", "17.9.2026", {
        "bs": ["Čitač sajtova (yt-dlp) se ažurira odvojeno od aplikacije."],
        "en": ["The site reader (yt-dlp) is updated separately from the app."],
        "de": ["Der Seiten-Reader (yt-dlp) wird getrennt von der App aktualisiert."],
        "es": ["El lector de sitios (yt-dlp) se actualiza aparte de la aplicación."],
        "fr": ["Le lecteur de sites (yt-dlp) est mis à jour séparément de l'application."],
    }),
    ("0.5.3", "17.9.2026", {
        "bs": ["Prenos uživo (LIVE) se ne preuzima, pa nema beskrajnog učitavanja."],
        "en": ["Live streams are not downloaded, so there is no endless loading."],
        "de": ["Livestreams werden nicht heruntergeladen, also kein endloses Laden."],
        "es": ["Las transmisiones en directo no se descargan, así que no hay carga infinita."],
        "fr": ["Les directs ne sont pas téléchargés, donc plus de chargement sans fin."],
    }),
    ("0.5.2", "17.9.2026", {
        "bs": ["Ispravljene ikonice dodatka za browser."],
        "en": ["Fixed the browser extension icons."],
        "de": ["Symbole der Browsererweiterung korrigiert."],
        "es": ["Corregidos los iconos de la extensión del navegador."],
        "fr": ["Icônes de l'extension du navigateur corrigées."],
    }),
    ("0.5.1", "17.9.2026", {
        "bs": ["Instaler na 5 jezika i automatsko ažuriranje (Pomoć → Provjeri ažuriranje)."],
        "en": ["Installer in 5 languages and automatic updates (Help → Check for updates)."],
        "de": ["Installationsprogramm in 5 Sprachen und automatische Updates (Hilfe → Nach Updates suchen)."],
        "es": ["Instalador en 5 idiomas y actualizaciones automáticas (Ayuda → Buscar actualizaciones)."],
        "fr": ["Installateur en 5 langues et mises à jour automatiques (Aide → Rechercher des mises à jour)."],
    }),
]


def entries(language: str) -> list[tuple[str, str, list[str]]]:
    """(verzija, datum, stavke) na traženom jeziku; nepoznat jezik dobija engleski."""
    return [(version, date, notes.get(language) or notes["en"]) for version, date, notes in CHANGES]


def to_html(language: str, current: str) -> str:
    parts = []
    for version, date, items in entries(language):
        marker = " ←" if version == current else ""
        parts.append(f"<h3 style='margin:12px 0 4px'>{escape(version)}"
                     f"<span style='color:#7a7a7a;font-weight:normal'> — {escape(date)}{marker}</span></h3>")
        parts.append("<ul style='margin-top:0'>" + "".join(f"<li>{escape(item)}</li>" for item in items) + "</ul>")
    return "".join(parts)


def release_notes(version: str, language: str = "bs") -> str:
    """Tekst za opis izdanja na GitHub-u."""
    for entry_version, _date, items in entries(language):
        if entry_version == version:
            return "\n".join(f"- {item}" for item in items)
    raise KeyError(version)
